name: modal
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  scoped_model: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true